help:
  app_name: dmg
  header: == ${hydra.help.app_name} ==
  template: |-
    ${hydra.help.header}

    PyTorch-based differentiable modeling framework developed by MHPI.

    ${hydra.help.footer}
  footer: |-
    Powered by Hydra (https://hydra.cc)
    Use --hydra-help to view Hydra-specific help
job:
  name: ${name}
  chdir: True
run:
  dir: ${hydra:runtime.cwd}/output/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
output_subdir: configs
sweep:
  dir: multirun
  subdir: ${hydra.job.override_dirname}
