defaults:
    - _self_
    - hydra: settings
    - observations: none


## General -------------------------------#
mode: train
multimodel_type: none
random_seed: 111111
device: cuda
gpu_id: 0

data_loader:
data_sampler: 
trainer: trainer

save_path: ../results


## Training ------------------------------#
train:
    start_time: 2000/01/01
    end_time: 2000/12/31
    target: [y_var]
    optimizer: Adadelta
    batch_size: 100
    epochs: 50
    start_epoch: 0
    save_epoch: 5


## Testing -------------------------------#
test:
    start_time: 2001/01/01
    end_time: 2001/12/31
    batch_size: 100
    test_epoch: 50


## Loss Function -------------------------#
loss_function:
    model: RmseLossComb
    

## dPL Model -----------------------------#
dpl_model:
    rho: 365
    
    phy_model:
        model: [None_model]
        nmul: 16
        warm_up: 365
        dynamic_params:
            None_model: [z1, z2]

        forcings: [
            x1_var,
            x2_var
        ]
        attributes: [
            attr1,
            attr2
        ]

    nn_model:
        model: LSTM
        dropout: 0.5
        hidden_size: 256
        learning_rate: 1.0
        
        forcings: [
            x1_var,
            x2_var
        ]
        attributes: [
            attr1,
            attr2
        ]
